// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xodfelprpwacbdmklqux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvZGZlbHBycHdhY2JkbWtscXV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NTYyNTQsImV4cCI6MjA1MzEzMjI1NH0.aIej1dphJN_xvMr0hIcJSFfANOt-RLUxDl_0EPhvs-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);